language: android
android:
  components:
  - platform-tools
  - build-tools-28.0.3
  - android-28
  - extra-google-google_play_services
dist: trusty
licenses:
- android-sdk-preview-license-.+
- android-sdk-license-.+
- google-gdk-license-.+
jdk: oraclejdk8
branches:
  only:
  - master
  - develop
  - /^feature\/.*$/
  - /^fix\/.*$/
  - /^\d+\.\d+(\.\d+)?(-\S*)?$/
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
before_install:
- chmod +x gradlew
- chmod +x gradle/release-patch.sh
stages:
  - name: deploy
    if: branch =~ /^\d+\.\d+(\.\d+)?$/
  - name: release
    if: branch = master && pull_request = "false"
jobs:
  include:
  - stage: build
    script: ./gradlew gdx-fireapp-android:assembleRelease
  - script: ./gradlew gdx-fireapp-core:jar
  - script: ./gradlew gdx-fireapp-ios:jar
  - script: ./gradlew gdx-fireapp-html:jar
  - stage: test
    script: ./gradlew test
  - stage: release
    script: ./gradle/release-patch.sh
  - stage: deploy
    script: ./gradlew gdx-fireapp-android:assembleRelease
  - script: ./gradlew publishToMavenLocal -Pversion=$TRAVIS_BRANCH
  - script: ./gradlew bintrayUpload -Pversion=$TRAVIS_BRANCH
    env:
      - BINTRAY_USER=mk-5
      - secure: "FV7WxKvLlG3cKKLmGaypquqXkH0qErYQDkvN6pgP1kI8rKPWCdG4NPmFhGxzJ0PoV3n1/hWWuyvcVCm9tC1dOOzEex+qWYE/GnyRhNaQ+2+Z64/R2i8xprJG1RPDL+Cv6JTftNK3UQpzaCxx2mSwSyWTpmSfYnlaCYRhOH5RLCC+pxzkcHq8ixV4GWIm+Ntm6YxSpvbvr+7CYHx0tx/4zEEFdNtIOvz1icWrt3MYs+pYQQDHv7RwVocgps9AZuhHK6gdFAx7YEsG14a4KP8cRyN/QJyR2QyrrXWFBa+yCFFVCDc1Z0gw8/0LZq/Y0O+DjBlDe+Lkjd4X5EKnw53tAB935hHNCi4E9Ui+8tPfWSfegkUzogfxsJtS0leoTwUhN2ITvuf4bMAH2lrROr6c9gk+HZLeOuBTOicCh9R4wOsF4W0ZOQS1rs0OtfGiCAwBksAMA+i2IVPU24lks9wB61TtBHL65DOZyhyn2PYKBfUznMHjjFC03S0/f2CihBzLyzK/cS+6PpyRd3OIMYvQ8liAH6jgAWhwk5fJf3jcZPhXQzjUUxe75eUebCtGGRZO2NV3nm6VKOaQOXr4t1TAMSRkCOHoVpsdOLNQq7lfvejATzZUvzLBMrYDweik/sfIYMwrZHjzXPxtOLs33vxf57Y9UvH6Wh2LudPfSSJQ5W8="